
spring.application.name=CadastroDeNinjas

# Habilita o Console do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuração do Banco em Memória
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Faz o Hibernate criar as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true